export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const GET_PROJECT_TASKS = 'GET_PROJECT_TASKS';
